# Site settings
title: avpet
email: avpet@hushmail.com
description: > # this means to ignore newlines until "baseurl:"
  various trifles
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  avpet

# Build settings
markdown: kramdown
